# This rule is not used by the project node-label-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over nlp.lento.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: node-label-controller
    app.kubernetes.io/managed-by: kustomize
  name: nodelabelpolicy-admin-role
rules:
- apiGroups:
  - nlp.lento.dev
  resources:
  - nodelabelpolicies
  verbs:
  - '*'
- apiGroups:
  - nlp.lento.dev
  resources:
  - nodelabelpolicies/status
  verbs:
  - get
